[0m19:03:54.213453 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f7a6210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f724890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f9141a0>]}


============================== 19:03:54.217298 | 59f9cd97-c886-44d1-915c-37fe9be0b2f1 ==============================
[0m19:03:54.217298 [info ] [MainThread]: Running with dbt=1.8.8
[0m19:03:54.217692 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/antonresetnak/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --target prod', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:03:54.218044 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/antonresetnak/weather-insights/dags/transform/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:03:54.221361 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.07372525, "process_user_time": 0.768022, "process_kernel_time": 0.119066, "process_mem_max_rss": "97976320", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:03:54.221753 [debug] [MainThread]: Command `dbt run` failed at 19:03:54.221663 after 0.07 seconds
[0m19:03:54.221978 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f9141a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f9160c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f914680>]}
[0m19:03:54.222159 [debug] [MainThread]: Flushing usage events
[0m20:10:00.921972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10da66b70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f7645f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f7642f0>]}


============================== 20:10:00.926987 | 19450550-aa40-476f-8192-18d1b40710a3 ==============================
[0m20:10:00.926987 [info ] [MainThread]: Running with dbt=1.8.8
[0m20:10:00.927480 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/antonresetnak/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run --select tag:transform', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:10:00.927862 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/antonresetnak/weather-insights/dags/transform/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:10:00.930229 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08589442, "process_user_time": 0.798827, "process_kernel_time": 0.337206, "process_mem_max_rss": "96505856", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:10:00.930807 [debug] [MainThread]: Command `dbt run` failed at 20:10:00.930689 after 0.09 seconds
[0m20:10:00.931168 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f72fce0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f5a6720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f01e420>]}
[0m20:10:00.931539 [debug] [MainThread]: Flushing usage events
