[0m19:41:36.207242 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11190e3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d5c9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d5c6b0>]}


============================== 19:41:36.211191 | 6fd6c368-e95c-4f11-839a-37397e4a8734 ==============================
[0m19:41:36.211191 [info ] [MainThread]: Running with dbt=1.8.8
[0m19:41:36.211586 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/antonresetnak/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': '/Users/antonresetnak/weather-insights/dags/transform/dbt/meta', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'meta', 'invocation_command': 'dbt run --threads 50 --target prod --target-path meta --log-path meta --full-refresh', 'send_anonymous_usage_stats': 'True'}
[0m19:41:36.211941 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/antonresetnak/weather-insights/dags/transform/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:41:36.218842 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.10284279, "process_user_time": 0.792238, "process_kernel_time": 0.129468, "process_mem_max_rss": "98312192", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:41:36.219381 [debug] [MainThread]: Command `dbt run` failed at 19:41:36.219287 after 0.10 seconds
[0m19:41:36.219633 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d5c6b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d5c800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d5ca70>]}
[0m19:41:36.219844 [debug] [MainThread]: Flushing usage events
